DROP TABLE IF EXISTS workout;
DROP TABLE IF EXISTS exercise;
DROP TABLE IF EXISTS workoutExercise;
DROP TABLE IF EXISTS loggedWorkout;
DROP TABLE IF EXISTS loggedWorkoutExercise;

CREATE TABLE IF NOT EXISTS workout (
    workoutId INTEGER  PRIMARY KEY AUTOINCREMENT,
    workoutName TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS exercise (
    exerciseId INTEGER PRIMARY KEY AUTOINCREMENT,
    exerciseName TEXT NOT NULL,
    muscleGroup TEXT NOT NULL,
    requiresGym INTEGER NOT NULL CHECK(requiresGym IN (0, 1)),
    gifFileName TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS workoutExercise (
    workoutId INTEGER NOT NULL,
    exerciseId INTEGER NOT NULL,
    sets INTEGER NOT NULL,
    isOrder INTEGER NOT NULL,
    PRIMARY KEY (workoutId, exerciseId),
    FOREIGN KEY (workoutId) REFERENCES workout(workoutId),
    FOREIGN KEY (exerciseId) REFERENCES exercise(exerciseId)
);

CREATE TABLE IF NOT EXISTS loggedWorkout (
    loggedWorkoutId INTEGER PRIMARY KEY AUTOINCREMENT,
    workoutId INTEGER NOT NULL,
    startTime TEXT NOT NULL,
    endTime TEXT,
    FOREIGN KEY (workoutId) REFERENCES workout(workoutId)
);

CREATE TABLE IF NOT EXISTS loggedWorkoutExercise (
    loggedWorkoutId INTEGER NOT NULL,
    exerciseId INTEGER NOT NULL,
    workoutId INTEGER NOT NULL,
    sets INTEGER NOT NULL,
    isOrder INTEGER NOT NULL,
    reps INT,
    weight INT,
    minutes INT,
    PRIMARY KEY (loggedWorkoutId, exerciseId),
    FOREIGN KEY (loggedWorkoutId) REFERENCES loggedWorkout(loggedWorkoutId),
    FOREIGN KEY (exerciseId) REFERENCES workoutExercise(exerciseId),
    FOREIGN KEY (workoutId) REFERENCES workoutExercise(workoutId)
);

/*Data for exercises. This is a permanent part of the DB*/
INSERT INTO exercise
    (exerciseName, muscleGroup, requiresGym, gifFileName)
VALUES
    ('Stick Drill Plyometrics', 'Cardio', False, '1-2-Stick-Drill-Plyometrics.gif'),
    ('45 Degree Incline Row', 'Back', True, '45-Degree-Incline-Row.gif'),
    ('Lever Pec Deck Fly', 'Chest', True, '10301301-Lever-Pec-Deck-Fly_Chest_720.gif'),
    ('Ab Coaster Machine', 'Abs', True, 'Ab-Coaster-Machine.gif'),
    ('Abdominal Stretch', 'Abs', False, 'abdominal-stretch.gif'),
    ('Above Head Chest Stretch', 'Chest', False, 'Above-Head-Chest-Stretch.gif'),
    ('Ab Roller Crunch', 'Abs', False, 'Ab-Roller-Crunch.gif'),
    ('Ab Straps Leg Raise', 'Abs', True, 'Ab-Straps-Leg-Raise.gif'),
    ('Across Chest Shoulder Stretch', 'Shoulders', False, 'Across-Chest-Shoulder-Stretch.gif'),
    ('Adductor Magnus Stretch', 'Legs', False, 'Adductor-Magnus-Stretch.gif'),
    ('Alternate Dumbbell Bench Press', 'Chest', True, 'Alternate-Dumbbell-Bench-Press.gif'),
    ('Alternate Leg Raises', 'Abs', False, 'Alternate-Leg-Raises.gif'),
    ('Alternate Lying Floor Leg Raise', 'Abs', False, 'Alternate-Lying-Floor-Leg-Raise.gif'),
    ('Alternating Dumbbell Front Raise', 'Shoulders', True, 'Alternating-Dumbbell-Front-Raise.gif'),
    ('Arm Blaster Hammer Curl', 'Biceps', True, 'Arm-Blaster-Hammer-Curl.gif'),
    ('Arm Circles', 'Shoulders', False, 'arm-circles.gif'),
    ('Arm Circles Shoulders', 'Shoulders', False, 'Arm-Circles_Shoulders.gif'),
    ('Arm Scissors', 'Shoulders', False, 'Arm-Scissors.gif'),
    ('Arnold Press', 'Shoulders', True, 'Arnold-Press.gif'),
    ('Assisted Triceps Dips', 'Triceps', True, 'Asisted-Triceps-Dips.gif'),
    ('Assault AirBike', 'Cardio', True, 'Assault-AirBike.gif'),
    ('Assault Air Runner', 'Cardio', True, 'Assault-Air-Runner.gif'),
    ('Assisted Chest Dip', 'Chest', True, 'Assisted-Chest-Dip.gif'),
    ('Assisted Pull-up', 'Back', True, 'Assisted-Pull-up.gif'),
    ('Astride Jumps', 'Legs', False, 'Astride-Jumps.gif'),
    ('Back Pec Stretch', 'Chest', False, 'Back-Pec-Stretch.gif'),
    ('Backward Jumping', 'Cardio', False, 'Backward-Jumping.gif'),
    ('Backwards Running', 'Cardio', False, 'Backwards-Running.gif'),
    ('Band Assisted Sprinter Run', 'Cardio', False, 'Band-Assisted-Sprinter-Run.gif'),
    ('Band Biceps Curl', 'Biceps', False, 'Band-Biceps-Curl.gif'),
    ('Band Pull Apart', 'Shoulders', False, 'Band-pull-apart.gif'),
    ('Barbell Pullover', 'Back', True, 'Barbell-Pullover.gif'),
    ('Barbell Sumo Squat', 'Legs', True, 'Barbell-Sumo-Squat.gif'),
    ('Barbell Alternate Biceps Curl', 'Biceps', True, 'Barbell-Alternate-Biceps-Curl.gif'),
    ('Barbell Bench Press', 'Chest', True, 'Barbell-Bench-Press.gif'),
    ('Barbell Bent Over Row', 'Back', True, 'Barbell-Bent-Over-Row.gif'),
    ('Barbell Bulgarian Split Squat', 'Legs', True, 'Barbell-Bulgarian-Split-Squat.gif'),
    ('Barbell Clean and Press', 'Cardio', True, 'Barbell-Clean-and-Press-.gif'),
    ('Barbell Curl', 'Biceps', True, 'Barbell-Curl.gif'),
    ('Barbell Curl On Arm Blaster', 'Biceps', True, 'Barbell-Curl-On-Arm-Blaster.gif'),
    ('Barbell Deadlift', 'Legs', True, 'Barbell-Deadlift.gif'),
    ('Barbell Drag Curl', 'Biceps', True, 'Barbell-Drag-Curl.gif'),
    ('Barbell Finger Curl', 'Biceps', True, 'Barbell-Finger-Curl.gif'),
    ('Barbell Good Morning', 'Legs', True, 'Barbell-Good-Morning.gif'),
    ('Barbell Hack Squat', 'Legs', True, 'Barbell-Hack-Squat.gif'),
    ('Barbell Lateral Lunge', 'Legs', True, 'Barbell-Lateral-Lunge.gif'),
    ('Barbell Lunge', 'Legs', True, 'Barbell-Lunge.gif'),
    ('Barbell One-Arm Floor Press', 'Chest', True, 'Barbell-One-Arm-Floor-Press.gif'),
    ('Barbell Rack Pull', 'Back', True, 'barbell-rack-pull.gif'),
    ('Barbell Rear Delt Raise', 'Shoulders', True, 'Barbell-Rear-Delt-Raise.gif'),
    ('Barbell Reverse Curl', 'Biceps', True, 'Barbell-Reverse-Curl.gif'),
    ('Barbell Reverse Wrist Curl', 'Forearms', True, 'Barbell-Reverse-Wrist-Curl.gif'),
    ('Barbell Reverse Wrist Curl Over a Bench', 'Forearms', True, 'Barbell-Reverse-Wrist-Curl-Over-a-Bench.gif'),
    ('Barbell Romanian Deadlift', 'Legs', True, 'Barbell-Romanian-Deadlift.gif'),
    ('Barbell Seated Calves Raise', 'Calves', True, 'Barbell-Seated-Calves-Raise.gif'),
    ('Barbell Seated Twist', 'Abs', True, 'Barbell-Seated-Twist.gif'),
    ('Barbell Shoulder Press', 'Shoulders', True, 'Barbell-Shoulder-Press.gif'),
    ('Barbell Shrug', 'Traps', True, 'Barbell-Shrug.gif'),
    ('Barbell Side Bend', 'Abs', True, 'Barbell-Side-Bend.gif'),
    ('Barbell Squat', 'Legs', True, 'BARBELL-SQUAT.gif'),
    ('Barbell Standing Military Press', 'Shoulders', True, 'Barbell-Standing-Military-Press.gif'),
    ('Barbell Step-Up', 'Legs', True, 'Barbell-Step-Up.gif'),
    ('Barbell Sumo Deadlift', 'Legs', True, 'Barbell-Sumo-Deadlift.gif'),
    ('Barbell Triceps Extension', 'Triceps', True, 'Barbell-Triceps-Extension.gif'),
    ('Barbell Upright Row', 'Shoulders', True, 'Barbell-Upright-Row.gif'),
    ('Barbell Wrist Curl', 'Forearms', True, 'barbell-Wrist-Curl.gif'),
    ('Battle Rope', 'Cardio', True, 'Battle-Rope.gif'),
    ('Bear Crawl', 'Cardio', False, 'Bear-Crawl.gif'),
    ('Behind The Back Barbell Shrug', 'Traps', True, 'Behind-The-Back-Barbell-Shrug-Reverse-Barbell-Shrug.gif'),
    ('Behind The Back Barbell Wrist Curl', 'Forearms', True, 'Behind-The-Back-Barbell-Wrist-Curl.gif'),
    ('Bench Dips', 'Triceps', True, 'Bench-Dips.gif'),
    ('Bench Press Machine Standing Calves Raise', 'Calves', True, 'Bench-Press-Machine-Standing-Calves-Raise.gif'),
    ('Bench Side Bend', 'Abs', True, 'Bench-Side-Bend.gif'),
    ('Bench Supported Dumbbell External Rotation', 'Shoulders', True, 'Bench-Supported-Dumbbell-External-Rotation.gif'),
    ('Bent Over Barbell Reverse Raise', 'Back', True, 'Bent-Over-Barbell-Reverse-Raise.gif'),
    ('Bent Over Dumbbell Row', 'Back', True, 'Bent-Over-Dumbbell-Row.gif'),
    ('Bent Over Lateral Raise', 'Shoulders', True, 'Bent-Over-Lateral-Raise.gif'),
    ('Bent Over Rear Delt Fly (Gymstick)', 'Shoulders', True, 'Bent-Over-Rear-Delt-Fly-Gymstick.gif'),
    ('Bent Over Reverse Cable Fly', 'Back', True, 'Bent-Over-Reverse-Cable-Fly.gif'),
    ('Bent Over Twist', 'Abs', False, 'Bent-Over-Twist.gif'),
    ('Bicep Curl Machine', 'Biceps', True, 'Bicep-Curl-Machine.gif'),
    ('Biceps Leg Concentration Curl', 'Biceps', True, 'Biceps-Leg-Concentration-Curl.gif'),
    ('Bicycle Crunch', 'Abs', False, 'Bicycle-Crunch.gif'),
    ('Bike', 'Cardio', False, 'Bike.gif'),
    ('Boat Pose Stretch', 'Abs', False, 'Boat-Pose-Stretch.gif'),
    ('Body Ups', 'Cardio', False, 'Body-Ups.gif'),
    ('Bodyweight Lunges', 'Legs', False, 'bodyweight-lunges.gif'),
    ('Bodyweight Military Press', 'Shoulders', False, 'Bodyweight-Military-Press.gif'),
    ('Bodyweight Squat', 'Legs', False, 'Bodyweight-Squat.gif'),
    ('Bodywheight Sumo Squat', 'Legs', False, 'BODYWEIGHT-SUMO-SQUAT.gif'),
    ('Bodyweight Walking Lunge', 'Legs', False, 'bodyweight-walking-lunge.gif'),
    ('Bodyweight Windmill', 'Abs', False, 'Bodyweight-Windmill.gif'),
    ('Boxer Shuffle Cardio', 'Cardio', False, 'Boxer-Shuffle-Cardio.gif'),
    ('Boxing Right Cross with Boxing Bag', 'Shoulders', True, 'Boxing-Right-Cross-with-boxing-bag.gif'),
    ('Box Jump 1 to 2', 'Legs', False, 'Box-Jump-1-to-2.gif'),
    ('Box Jump 2 to 1', 'Legs', False, 'Box-Jump-2-to-1.gif'),
    ('Box Jump to Pistol Squat', 'Legs', False, 'Box-Jump-to-Pistol-Squat.gif'),
    ('Brachialis Pull-up', 'Forearms', False, 'Brachialis-Pull-up.gif'),
    ('Briskly Walking', 'Cardio', False, 'Briskly-Walking.gif'),
    ('Bulgarian Split Squat Jump', 'Legs', False, 'Bulgarian Split Squat Jump.gif'),
    ('Burpees', 'Cardio', False, 'burpees.gif'),
    ('Butt Kicks', 'Cardio', False, 'Butt-Kicks.gif'),
    ('Cable Incline Biceps Curl', 'Biceps', True, 'Cable Incline Biceps Curl.gif'),
    ('Cable Two Arm Curl on Incline Bench', 'Biceps', True, 'Cable Two Arm Curl on Incline Bench.gif'),
    ('Cable Bent Over Row', 'Back', True, 'Cable-Bent-Over-Row.gif'),
    ('Cable Concentration Curl', 'Biceps', True, 'Cable-Concentration-Curl.gif'),
    ('Cable Concentration Extension on Knee', 'Biceps', True, 'Cable-Concentration-Extension-on-knee.gif'),
    ('Cable Crossover', 'Chest', True, 'Cable-Crossover.gif'),
    ('Cable Crossover Lat Pulldown', 'Back', True, 'Cable-Crossover-Lat-Pulldown.gif'),
    ('Cable Curl', 'Biceps', True, 'cable-curl.gif'),
    ('Cable External Shoulder Rotation', 'Shoulders', True, 'Cable-External-Shoulder-Rotation.gif'),
    ('Cable Front Raise', 'Shoulders', True, 'Cable-Front-Raise.gif'),
    ('Cable Hips Adduction', 'Legs', True, 'Cable-Hips-Adduction.gif'),
    ('Cable Incline Triceps Extension', 'Triceps', True, 'Cable-Incline-Triceps-Extension.gif'),
    ('Cable Internal Shoulder Rotation', 'Shoulders', True, 'Cable-Internal-Shoulder-Rotation.gif'),
    ('Cable Kneeling Biceps Curl', 'Biceps', True, 'Cable-Kneeling-Biceps-Curl.gif'),
    ('Cable Lateral Raise', 'Shoulders', True, 'Cable-Lateral-Raise.gif'),
    ('Cable Lying Triceps Extensions', 'Triceps', True, 'Cable-Lying-Triceps-Extensions.gif'),
    ('Cable One Arm Lat Pulldown', 'Back', True, 'Cable-One-Arm-Lat-Pulldown.gif'),
    ('Cable One Arm Overhead Triceps Extension', 'Triceps', True, 'Cable-One-Arm-Overhead-Triceps-Extension.gif'),
    ('Cable One Arm Wrist Curl On Floor', 'Forearms', True, 'Cable-One-Arm-Wrist-Curl-On-Floor.gif'),
    ('Cable Preacher Curls', 'Biceps', True, 'cable-preacher-curls.gif'),
    ('Cable Pulldown Bicep Curl', 'Biceps', True, 'Cable-Pulldown-Bicep-Curl.gif'),
    ('Cable Rear Delt Fly', 'Shoulders', True, 'cable-rear-delt-fly.gif'),
    ('Cable Rear Drive', 'Legs', True, 'Cable-Rear-Drive.gif'),
    ('Cable Rear Pulldown', 'Back', True, 'Cable-Rear-Pulldown.gif'),
    ('Cable Reverse Grip EZ-bar Biceps Curl', 'Biceps', True, 'Cable-Reverse-Grip-EZ-bar-Biceps-Curl.gif'),
    ('Cable Rope Overhead Triceps Extension', 'Triceps', True, 'Cable-Rope-Overhead-Triceps-Extension.gif'),
    ('Cable Seated Cross Arm Twist', 'Abs', True, 'Cable-Seated-Cross-Arm-Twist.gif'),
    ('Cable Seated Neck Extension with Head Harness', 'Neck', True, 'Cable-Seated-Neck-Extension-with-head-harness.gif'),
    ('Cable Seated Neck Flexion with Head Harness', 'Neck', True, 'Cable-Seated-Neck-Flexion-with-head-harness.gif'),
    ('Cable Seated Pullover', 'Chest', True, 'Cable-Seated-Pullover.gif'),
    ('Cable Seated Shoulder Internal Rotation', 'Shoulders', True, 'Cable-Seated-Shoulder-Internal-Rotation.gif'),
    ('Cable Shoulder Press', 'Shoulders', True, 'Cable-Shoulder-Press.gif'),
    ('Cable Shrug', 'Traps', True, 'Cable-Shrug.gif'),
    ('Cable Side Bend', 'Abs', True, 'Cable-Side-Bend.gif'),
    ('Cable Side Triceps Extension', 'Triceps', True, 'Cable-Side-Triceps-Extension.gif'),
    ('Cable Squat', 'Legs', True, 'Cable-Squat.gif'),
    ('Cable Straight Arm Pulldown', 'Back', True, 'Cable-Straight-Arm-Pulldown.gif'),
    ('Cable Tricep Kickback', 'Triceps', True, 'Cable-Tricep-Kickback.gif'),
    ('Cable Upper Chest Crossovers', 'Chest', True, 'Cable-Upper-Chest-Crossovers.gif'),
    ('Cable Upright Row', 'Shoulders', True, 'Cable-Upright-Row.gif'),
    ('Cable Y Raise', 'Shoulders', True, 'cable-y-raise.gif'),
    ('Calves Raise with Resistance Band', 'Calves', False, 'Calves-Raise-with-Resistance-Band.gif'),
    ('Calves Stretch with Rope', 'Calves', False, 'Calves-Stretch-with-Rope.gif'),
    ('Calves Stretch Static Position', 'Calves', False, 'Calves-Stretch-Static-Position.gif'),
    ('Captains Chair Leg Raise', 'Abs', True, 'Captains-Chair-Leg-Raise.gif'),
    ('Chair Dips', 'Triceps', False, 'CHAIR-DIPS.gif'),
    ('Chest Dips', 'Chest', True, 'Chest-Dips.gif'),
    ('Chin Up Around the Bar', 'Back', True, 'Chin Up Around the Bar.gif'),
    ('Chin Tuck', 'Neck', False, 'Chin-Tuck.gif'),
    ('Chin Up', 'Back', True, 'Chin-Up.gif'),
    ('Clap Push-Up', 'Chest', False, 'Clap-Push-Up.gif'),
    ('Close Grip Dumbbell Press', 'Chest', True, 'Close-Grip Dumbbell Press.gif'),
    ('Close Grip Barbell Curl', 'Biceps', True, 'close-grip-barbell-curl.gif'),
    ('Close Grip Bench Press', 'Chest', True, 'Close-Grip-Bench-Press.gif'),
    ('Clos Grip Cable Row', 'Back', True, 'close-grip-cable-row.gif'),
    ('Close Grip Chin-Up', 'Back', True, 'Close-Grip-Chin-Up.gif'),
    ('Close Grip Dumbbell Press', 'Chest', True, 'Close-Grip-Dumbbell-Press.gif'),
    ('Close Grip Incline Dumbbell Press', 'Chest', True, 'Close-grip-Incline-Dumbbell-Press.gif'),
    ('Close Grip Lat Pulldown', 'Back', True, 'Close-Grip-Lat-Pulldown.gif'),
    ('Close Grip Z Bar Curl', 'Biceps', True, 'Close-Grip-Z-Bar-Curl.gif'),
    ('Concentration Curl', 'Biceps', True, 'Concentration-Curl.gif'),
    ('Cossack Squat', 'Legs', False, 'Cossack-Squat.gif'),
    ('Crab Twist Toe Touch', 'Abs', False, 'Crab-Twist-Toe-Touch.gif'),
    ('Cross Body Push-up', 'Chest', False, 'Cross Body Push-up.gif'),
    ('Cross Arm Push Up', 'Chest', False, 'Cross-Arm-Push-up.gif'),
    ('Cross Body Mountain Climber', 'Abs', False, 'Cross-Body-Mountain-Climber.gif'),
    ('Cross Cable Face Pull', 'Back', True, 'Cross-Cable-Face-Pull.gif'),
    ('Cross Crunch', 'Abs', False, 'Cross-Crunch.gif'),
    ('Crouching Heel Back Calves Stretch', 'Calves', False, 'Crouching-Heel-Back-Calves-Stretch.gif'),
    ('Crunch', 'Abs', False, 'Crunch.gif'),
    ('Crunch With Leg Raise', 'Abs', False, 'Crunch-With-Leg-Raise.gif'),
    ('Curtsey Squat', 'Legs', False, 'Curtsey-Squat.gif'),
    ('Dead Bug', 'Abs', False, 'Dead-Bug.gif'),
    ('Decline Barbell Bench Press', 'Chest', True, 'Decline-Barbell-Bench-Press.gif'),
    ('Decline Cable Fly', 'Chest', True, 'Decline-Cable-Fly.gif'),
    ('Decline Chest Press Machine', 'Chest', True, 'Decline-Chest-Press-Machine.gif'),
    ('Decline Close Grip Bench To Skull Crusher', 'Triceps', True, 'Decline-Close-Grip-Bench-To-Skull-Crusher.gif'),
    ('Decline Dumbbell Fly', 'Chest', True, 'Decline-Dumbbell-Fly.gif'),
    ('Decline Dumbbell Press', 'Chest', True, 'Decline-Dumbbell-Press.gif'),
    ('Decline Push Up', 'Chest', False, 'Decline-Push-Up.gif'),
    ('Decline Sit Up', 'Abs', False, 'Decline-Sit-up.gif'),
    ('Depth Jump to Hurdle Hop', 'Legs', False, 'Depth-Jump-to-Hurdle-Hop.gif'),
    ('Diagonal Neck Stretch', 'Neck', False, 'Diagonal-Neck-Stretch.gif'),
    ('Diamond Push Up', 'Chest', False, 'Diamond-Push-up.gif'),
    ('Dips Between Chairs', 'Triceps', True, 'Dips-Between-Chairs.gif'),
    ('Dip Shrugs', 'Shoulders', True, 'Dip-Shrugs.gif'),
    ('Donkey Calves Raise', 'Calves', True, 'Donkey-Calves-Raise.gif'),
    ('Double Arm Dumbbell Curl', 'Biceps', True, 'Double-Arm-Dumbbell-Curl.gif'),
    ('Double Cable Front Raise', 'Shoulders', True, 'Double-Cable-Front-Raise.gif'),
    ('Double Cable Neutral Grip Lat Pulldown On Floor', 'Back', True, 'Double-Cable-Neutral-Grip-Lat-Pulldown-On-Floor.gif'),
    ('Double Leg Stretch', 'Abs', False, 'Double-Leg-Stretch.gif'),
    ('Drop Push Up', 'Chest', False, 'Drop-Push-Up.gif'),
    ('Dumbbell 4 Ways Lateral Raise', 'Shoulders', True, 'Dumbbell-4-Ways-Lateral-Raise.gif'),
    ('Dumbbell 6 Ways Raise', 'Shoulders', True, 'Dumbbell-6-Ways-Raise.gif'),
    ('Dumbbell Alternate Preacher Curl', 'Biceps', True, 'Dumbbell-Alternate-Preacher-Curl.gif'),
    ('Dumbbell Bent Arm Lateral Raise', 'Shoulders', True, 'Dumbbell-Bent-Arm-Lateral-Raise.gif'),
    ('Dumbbell Bent Over Reverse Row', 'Back', True, 'Dumbbell-Bent-Over-Reverse-Row.gif'),
    ('Dumbbell Bulgarian Split Squat', 'Legs', True, 'Dumbbell-Bulgarian-Split-Squat.gif'),
    ('Dumbbell Burpees', 'Cardio', True, 'Dumbbell-Burpees.gif'),
    ('Dumbbell Calves Raise', 'Calves', True, 'Dumbbell-Calves-Raise.gif'),
    ('Dumbbell Chest Supported Lateral Raises', 'Shoulders', True, 'Dumbbell-Chest-Supported-Lateral-Raises.gif'),
    ('Dumbbell Cuban External Rotation', 'Shoulders', True, 'Dumbbell-Cuban-External-Rotation.gif'),
    ('Dumbbell Cuban Press', 'Shoulders', True, 'dumbbell-cuban-press-.gif'),
    ('Dumbbell Curl', 'Biceps', True, 'Dumbbell-Curl.gif'),
    ('Dumbbell Curl On Arm Blaster', 'Biceps', True, 'Dumbbell-Curl-On-Arm-Blaster.gif'),
    ('Dumbbell Deadlifts', 'Legs', True, 'Dumbbell-Deadlifts.gif'),
    ('Dumbbell Decline One Arm Hammer Press', 'Chest', True, 'Dumbbell-Decline-One-Arm-Hammer-Press.gif'),
    ('Dumbbell Decline Shrug', 'Traps', True, 'Dumbbell-Decline-Shrug.gif'),
    ('Dumbbell Fly', 'Chest', True, 'Dumbbell-Fly.gif'),
    ('Dumbbell Front Raise', 'Shoulders', True, 'Dumbbell-Front-Raise.gif'),
    ('Dumbbell Goblet Squat', 'Legs', True, 'Dumbbell-Goblet-Squat.gif'),
    ('Dumbbell Good Morning', 'Back', True, 'Dumbbell-Good-Morning.gif'),
    ('Dumbbell High Curl', 'Biceps', True, 'Dumbbell-High-Curl.gif'),
    ('Dumbbell Incline T Raise', 'Shoulders', True, 'Dumbbell-Incline-T-Raise.gif'),
    ('Dumbbell Incline Two-Arm Extension', 'Triceps', True, 'Dumbbell-Incline-Two-Arm-Extension.gif'),
    ('Dumbbell Jump Squat', 'Legs', True, 'Dumbbell-Jump-Squat.gif'),
    ('Dumbbell Kickback', 'Triceps', True, 'Dumbbell-Kickback.gif'),
    ('Dumbbell Lateral Raise', 'Shoulders', True, 'Dumbbell-Lateral-Raise.gif'),
    ('Dumbbell One-Arm Preacher Curl', 'Biceps', True, 'Dumbbell-One-Arm-Preacher-Curl.gif'),
    ('Dumbbell One-Arm Row', 'Back', True, 'Dumbbell-One-Arm-Row.gif'),
    ('Dumbbell One-Arm Shrug', 'Traps', True, 'Dumbbell-One-Arm-Shrug.gif'),
    ('Dumbbell Overhead Triceps Extension', 'Triceps', True, 'Dumbbell-Overhead-Triceps-Extension.gif'),
    ('Dumbbell Pallof Press', 'Abs', True, 'Dumbbell-Pallof-Press.gif'),
    ('Dumbbell Pinch Press', 'Chest', True, 'Dumbbell-Pinch-Press.gif'),
    ('Dumbbell Plank Row', 'Back', True, 'Dumbbell-Plank-Row.gif'),
    ('Dumbbell Rear Delt Fly', 'Shoulders', True, 'Dumbbell-Rear-Delt-Fly.gif'),
    ('Dumbbell Rear Delt Raise', 'Shoulders', True, 'Dumbbell-Rear-Delt-Raise.gif'),
    ('Dumbbell Reverse Curl', 'Biceps', True, 'Dumbbell-Reverse-Curl.gif'),
    ('Dumbbell Reverse Wrist Curl', 'Forearms', True, 'Dumbbell-Reverse-Wrist-Curl.gif'),
    ('Dumbbell Reverse Wrist Curl Over A Bench', 'Forearms', True, 'Dumbbell-Reverse-Wrist-Curl-Over-a-Bench.gif'),
    ('Dumbbell Romanian Deadlift', 'Legs', True, 'Dumbbell-Romanian-Deadlift.gif'),
    ('Dumbbell Seated Calves Raise', 'Calves', True, 'Dumbbell-Seated-Calves-Raise.gif'),
    ('Dumbbell Seated Twist', 'Abs', True, 'Dumbbell-Seated-Twist.gif'),
    ('Dumbbell Shoulder Press', 'Shoulders', True, 'Dumbbell-Shoulder-Press.gif'),
    ('Dumbbell Shrug', 'Traps', True, 'Dumbbell-Shrug.gif'),
    ('Dumbbell Side Bend', 'Abs', True, 'Dumbbell-Side-Bend.gif'),
    ('Dumbbell Squat', 'Legs', True, 'Dumbbell-Squat.gif'),
    ('Dumbbell Straight Arm Pulldown', 'Back', True, 'Dumbbell-Straight-Arm-Pulldown.gif'),
    ('Dumbbell Tricep Kickback', 'Triceps', True, 'Dumbbell-Tricep-Kickback.gif'),
    ('Dumbbell Upper Chest Crossovers', 'Chest', True, 'Dumbbell-Upper-Chest-Crossovers.gif'),
    ('Dumbbell Upright Row', 'Shoulders', True, 'Dumbbell-Upright-Row.gif'),
    ('Dumbbell Y Raise', 'Shoulders', True, 'dumbbell-y-raise.gif'),
    ('Calves Stretch with Rope', 'Calves', False, 'Calves-Stretch-with-Rope.gif'),
    ('Calves Stretch Static Position', 'Calves', False, 'Calves-Stretch-Static-Position.gif'),
    ('Captains Chair Leg Raise', 'Abs', True, 'Captains-Chair-Leg-Raise.gif'),
    ('Chair Dips', 'Triceps', False, 'CHAIR-DIPS.gif'),
    ('Chest Dips', 'Chest', True, 'Chest-Dips.gif'),
    ('Chin Up Around the Bar', 'Back', True, 'Chin Up Around the Bar.gif'),
    ('Chin Tuck', 'Neck', False, 'Chin-Tuck.gif'),
    ('Chin Up', 'Back', True, 'Chin-Up.gif'),
    ('Clap Push Up', 'Chest', False, 'Clap-Push-Up.gif'),
    ('Close Grip Dumbbell Press', 'Chest', True, 'Close-Grip-Dumbbell-Press.gif'),
    ('Calves Raise with Resistance Band', 'Calves', False, 'Calves-Raise-with-Resistance-Band.gif'),
    ('Dumbbell Incline Shrug', 'Traps', True, 'Dumbbell-Incline-Shrug.gif'),
    ('Close Grip Barbell Curl', 'Biceps', True, 'close-grip-barbell-curl.gif'),
    ('Close-Grip Bench Press', 'Chest', True, 'Close-Grip-Bench-Press.gif'),
    ('Close Grip Cable Row', 'Back', True, 'close-grip-cable-row.gif'),
    ('Close Grip Chin Up', 'Back', True, 'Close-Grip-Chin-Up.gif'),
    ('Close Grip Dumbbell Press', 'Chest', True, 'Close-Grip-Dumbbell-Press.gif'),
    ('Close Grip Incline Dumbbell Press', 'Chest', True, 'close-grip-Incline-Dumbbell-Press.gif'),
    ('Close Grip Lat Pulldown', 'Back', True, 'Close-Grip-Lat-Pulldown.gif'),
    ('Close Grip Z Bar Curl', 'Biceps', True, 'Close-Grip-Z-Bar-Curl.gif'),
    ('Concentration Curl', 'Biceps', True, 'Concentration-Curl.gif'),
    ('Cossack Squat', 'Legs', False, 'Cossack-Squat.gif'),
    ('Crab Twist Toe Touch', 'Abs', False, 'Crab-Twist-Toe-Touch.gif'),
    ('Cross Body Push-up', 'Chest', False, 'Cross Body Push-up.gif'),
    ('Cross Arm Push-up', 'Chest', False, 'Cross-Arm-Push-up.gif'),
    ('Cross Body Mountain Climber', 'Abs', False, 'Cross-Body-Mountain-Climber.gif'),
    ('Cross Cable Face Pull', 'Shoulders', True, 'Cross-Cable-Face-Pull.gif'),
    ('Cross Crunch', 'Abs', False, 'Cross-Crunch.gif'),
    ('Crouching Heel Back Calves Stretch', 'Calves', False, 'Crouching-Heel-Back-Calves-Stretch.gif'),
    ('Crunch', 'Abs', False, 'Crunch.gif'),
    ('Crunch With Leg Raise', 'Abs', False, 'Crunch-With-Leg-Raise.gif'),
    ('Curtsey Squat', 'Legs', False, 'Curtsey-Squat.gif'),
    ('Dead Bug', 'Abs', False, 'Dead-Bug.gif'),
    ('Decline Barbell Bench Press', 'Chest', True, 'Decline-Barbell-Bench-Press.gif'),
    ('Decline Cable Fly', 'Chest', True, 'Decline-Cable-Fly.gif'),
    ('Decline Chest Press Machine', 'Chest', True, 'Decline-Chest-Press-Machine.gif'),
    ('Decline Close-Grip Bench To Skull Crusher', 'Triceps', True, 'Decline-Close-Grip-Bench-To-Skull-Crusher.gif'),
    ('Decline Dumbbell Fly', 'Chest', True, 'Decline-Dumbbell-Fly.gif'),
    ('Decline Dumbbell Press', 'Chest', True, 'Decline-Dumbell-Press.gif'),
    ('Decline Push-Up', 'Chest', False, 'Decline-Push-Up.gif'),
    ('Decline Sit-Up', 'Abs', False, 'Decline-Sit-up.gif'),
    ('Depth Jump to Hurdle Hop', 'Legs', True, 'Depth-Jump-to-Hurdle-Hop.gif'),
    ('Diagonal Neck Stretch', 'Neck', False, 'Diagonal-Neck-Stretch-360x360.png'),
    ('Diamond Push Up', 'Chest', False, 'Diamond-Push-up.gif'),
    ('Dips Between Chairs', 'Triceps', False, 'Dips-Between-Chairs.gif'),
    ('Dip Shrugs', 'Traps', True, 'Dip-Shrugs.gif'),
    ('Donkey Calves Raise', 'Calves', True, 'Donkey-Calves-Raise.gif'),
    ('Double Arm Dumbbell Curl', 'Biceps', True, 'Double-Arm-Dumbbell-Curl.gif'),
    ('Double Cable Front Raise', 'Shoulders', True, 'Double-Cable-Front-Raise.gif'),
    ('Double Cable Neutral Grip Lat Pulldown On Floor', 'Back', True, 'Double-Cable-Neutral-Grip-Lat-Pulldown-On-Floor.gif'),
    ('Double Leg Stretch', 'Legs', False, 'Double-Leg-Stretch.gif'),
    ('Drop Push Up', 'Chest', False, 'Drop-Push-Up.gif'),
    ('Dumbbell 4 Ways Lateral Raise', 'Shoulders', True, 'Dumbbell-4-Ways-Lateral-Raise.gif'),
    ('Dumbbell 6 Ways Raise', 'Shoulders', True, 'Dumbbell-6-Ways-Raise.gif'),
    ('Dumbbell Alternate Preacher Curl', 'Biceps', True, 'Dumbbell-Alternate-Preacher-Curl.gif'),
    ('Dumbbell Bent Arm Lateral Raise', 'Shoulders', True, 'Dumbbell-Bent-Arm-Lateral-Raise.gif'),
    ('Dumbbell Bent Over Reverse Row', 'Back', True, 'Dumbbell-Bent-Over-Reverse-Row.gif'),
    ('Dumbbell Bulgarian Split Squat', 'Legs', True, 'Dumbbell-Bulgarian-Split-Squat.gif'),
    ('Dumbbell Burpees', 'Cardio', True, 'Dumbbell-Burpees.gif'),
    ('Dumbbell Calves Raise', 'Calves', True, 'Dumbbell-Calves-Raise.gif'),
    ('Dumbbell Chest Supported Lateral Raises', 'Shoulders', True, 'Dumbbell-Chest-Supported-Lateral-Raises.gif'),
    ('Dumbbell Cuban External Rotation', 'Shoulders', True, 'Dumbbell-Cuban-External-Rotation.gif'),
    ('Dumbbell Cuban Press', 'Shoulders', True, 'dumbbell-cuban-press-.gif'),
    ('Dumbbell Curl', 'Biceps', True, 'Dumbbell-Curl.gif'),
    ('Dumbbell Curl On Arm Blaster', 'Biceps', True, 'Dumbbell-Curl-On-Arm-Blaster.gif'),
    ('Dumbbell Deadlifts', 'Legs', True, 'dumbbell-deadlifts.gif'),
    ('Dumbbell Decline One-Arm Hammer Press', 'Chest', True, 'Dumbbell-Decline-One-Arm-Hammer-Press.gif'),
    ('Dumbbell Decline Shrug', 'Traps', True, 'Dumbbell-Decline-Shrug.gif'),
    ('Dumbbell Fly', 'Chest', True, 'Dumbbell-Fly.gif'),
    ('Dumbbell Front Raise', 'Shoulders', True, 'Dumbbell-Front-Raise.gif'),
    ('Dumbbell Goblet Squat', 'Legs', True, 'Dumbbell-Goblet-Squat.gif'),
    ('Dumbbell Good Morning', 'Back', True, 'Dumbbell-Good-Morning.gif'),
    ('Dumbbell High Curl', 'Biceps', True, 'Dumbbell-High-Curl.gif'),
    ('Dumbbell Incline Shrug', 'Traps', True, 'Dumbbell-Incline-Shrug.gif'),
    ('Dumbbell Incline T-Raise', 'Shoulders', True, 'Dumbbell-Incline-T-Raise.gif'),
    ('Dumbbell Incline Two-Arm Extension', 'Triceps', True, 'Dumbbell-Incline-Two-Arm-Extension.gif'),
    ('Dumbbell Jump Squat', 'Legs', True, 'Dumbbell-Jump-Squat.gif'),
    ('Dumbbell Kickback', 'Triceps', True, 'Dumbbell-Kickback.gif'),
    ('Dumbbell Lateral Raise', 'Shoulders', True, 'Dumbbell-Lateral-Raise.gif'),
    ('Dumbbell Lateral Step-Up', 'Legs', True, 'Dumbbell-Lateral-Step-Up.gif'),
    ('Dumbbell Lateral to Front Raise', 'Shoulders', True, 'Dumbbell-Lateral-to-Front-Raise.gif'),
    ('Dumbbell Lunge', 'Legs', True, 'Dumbbell-Lunge.gif'),
    ('Dumbbell Lunges', 'Legs', True, 'dumbbell-lunges.gif'),
    ('Dumbbell Lying External Shoulder Rotation', 'Shoulders', True, 'Dumbbell-Lying-External-Shoulder-Rotation.gif'),
    ('Dumbbell Lying One-Arm Rear Lateral Raise', 'Shoulders', True, 'Dumbbell-Lying-One-Arm-Rear-Lateral-Raise.gif'),
    ('Dumbbell One Arm Reverse Grip Press', 'Chest', True, 'Dumbbell-One-Arm-Reverse-Grip-Press.gif'),
    ('Dumbbell One-Arm Shoulder Press', 'Shoulders', True, 'Dumbbell-One-Arm-Shoulder-Press.gif'),
    ('Dumbbell Preacher Curl', 'Biceps', True, 'Dumbbell-Preacher-Curl.gif'),
    ('Dumbbell Preacher Hammer Curl', 'Biceps', True, 'Dumbbell-Preacher-Hammer-Curl.gif'),
    ('Dumbbell Press', 'Chest', True, 'Dumbbell-Press-1.gif'),
    ('Dumbbell Pullover', 'Chest', True, 'Dumbbell-Pullover.gif'),
    ('Dumbbell Pullover On Stability Ball', 'Chest', True, 'Dumbbell-Pullover-On-Stability-Ball.gif'),
    ('Dumbbell Push Press', 'Shoulders', True, 'Dumbbell-Push-Press.gif'),
    ('Dumbbell Raise', 'Shoulders', True, 'Dumbbell-Raise.gif'),
    ('Dumbbell Rear Delt Row', 'Shoulders', True, 'Dumbbell-Rear-Delt-Row.gif'),
    ('Dumbbell Rear Lunge', 'Legs', True, 'Dumbbell-Rear-Lunge.gif'),
    ('Dumbbell Reverse Curl', 'Biceps', True, 'Dumbbell-Reverse-Curl.gif'),
    ('Dumbbell Reverse Fly', 'Back', True, 'Dumbbell-Reverse-Fly.gif'),
    ('Dumbbell Romanian Deadlift', 'Legs', True, 'Dumbbell-Romanian-Deadlift.gif'),
    ('Dumbbell Row', 'Back', True, 'Dumbbell-Row.gif'),
    ('Dumbbell Scaption', 'Shoulders', True, 'Dumbbell-Scaption.gif'),
    ('Dumbbell Scot Curl', 'Biceps', True, 'dumbbell-scot-curl.gif'),
    ('Dumbbell Scott Hammer Curl', 'Biceps', True, 'Dumbbell-Scott-Hammer-Curl.gif'),
    ('Dumbbell Seated Bent Over Rear Delt Row', 'Shoulders', True, 'Dumbbell-Seated-Bent-Over-Rear-Delt-Row.gif'),
    ('Dumbbell Seated Front and Back Tate Press', 'Triceps', True, 'Dumbbell-Seated-Front-and-Back-Tate-Press.gif'),
    ('Dumbbell Seated Gittleson Shrug', 'Traps', True, 'Dumbbell-Seated-Gittleson-Shrug.gif'),
    ('Dumbbell Seated Neutral Wrist Curl', 'Forearms', True, 'Dumbbell-Seated-Neutral-Wrist-Curl.gif'),
    ('Dumbbell Shoulder Press', 'Shoulders', True, 'Dumbbell-Shoulder-Press.gif'),
    ('Dumbbell Shrug', 'Traps', False, 'Dumbbell-Shrug.gif'),
    ('Dumbbell Side Lying Rear Delt Raise', 'Shoulders', True, 'Dumbbell-Side-Lying-Rear-Delt-Raise.gif'),
    ('Dumbbell Skull Crusher', 'Triceps', True, 'Dumbbell-Skull-Crusher.gif'),
    ('Dumbbell Split Jump', 'Legs', True, 'Dumbbell-Split-Jump.gif'),
    ('Dumbbell Squat', 'Legs', True, 'Dumbbell-Squat.gif'),
    ('Dumbbell Standing Palms In Press', 'Chest', True, 'Dumbbell-Standing-Palms-In-Press.gif'),
    ('Dumbbell Straight Leg Deadlift', 'Legs', True, 'Dumbbell-Straight-Leg-Deadlift.gif'),
    ('Dumbbell Sumo Deadlift', 'Legs', True, 'dumbbell-sumo-deadlift.gif'),
    ('Dumbbell Upright Row', 'Shoulders', True, 'Dumbbell-Upright-Row.gif'),
    ('Dumbbell Upward Fly', 'Chest', True, 'Dumbbell-Upward-Fly.gif'),
    ('Dumbbell V-up', 'Abs', True, 'Dumbbell-V-up.gif'),
    ('Dumbbell W-Press', 'Shoulders', True, 'Dumbbell-W-Press.gif'),
    ('Dumbbell Wrist Curl', 'Forearms', True, 'Dumbbell-Wrist-Curl.gif'),
    ('Dumbeel Step Up', 'Legs', True, 'Dumbeel-Step-Up.gif'),
    ('Dynamic Chest Stretch', 'Chest', False, 'Dynamic-Chest-Stretch.gif'),
    ('Elbow Flexion', 'Biceps', False, 'elbow-flexion.gif'),
    ('Elbow Reverse Push-Up', 'Triceps', False, 'Elbow-Reverse-Push-Up.gif'),
    ('Elbow To Knee Twists', 'Abs', False, 'Elbow-To-Knee-Twists.gif'),
    ('Elliptical Machine', 'Cardio', True, 'Elliptical-Machine.gif'),
    ('Exercise Ball Frog Crunch', 'Abs', False, 'Exercise-Ball-Frog-Crunch.gif'),
    ('Exercise Ball Supine Triceps Extension', 'Triceps', False, 'Exercise-Ball-Supine-Triceps-Extension.gif'),
    ('EZ Barbell Incline Triceps Extension', 'Triceps', True, 'EZ-Barbell-Incline-Triceps-Extension.gif'),
    ('EZ Bar Underhand Press', 'Chest', True, 'EZ-Bar-Underhand-Press.gif'),
    ('Face Pull', 'Shoulders', True, 'Face-Pull.gif'),
    ('Farmers Walk', 'Cardio', True, 'Farmers-walk_Cardio.gif'),
    ('Fast Feet Run', 'Cardio', False, 'Fast-Feet-Run.gif'),
    ('Feet and Ankle Rotation', 'Legs', False, 'Feet-and-Ankle-Rotation.gif'),
    ('Fish Pose (Matsyasana)', 'Back', False, 'Fish-Pose-Matsyasana.gif'),
    ('Flexor Incline Dumbbell Curls', 'Biceps', True, 'Flexor-Incline-Dumbbell-Curls.gif'),
    ('Floor Crunch', 'Abs', False, 'Floor-Crunch.gif'),
    ('Floor Hyperextension', 'Back', False, 'Floor-Hyperextension-1.gif'),
    ('Foam Roller Calves', 'Calves', False, 'Foam-Roller-Calves.gif'),
    ('Foam Roller Upper Back', 'Back', False, 'Foam-Roller-Upper-Back.gif'),
    ('Foot and Ankle Stretches', 'Calves', False, 'Foot-and-Ankle-Rotation.gif'),
    ('Front and Back Neck Stretch', 'Neck', False, 'Front-and-Back-Neck-Stretch.gif'),
    ('Front Plank with Arm and Leg Lift', 'Abs', False, 'Front-Plank-With-Arm-And-Leg-Lift.gif'),
    ('Front Plank with Arm Lift', 'Abs', False, 'Front-Plank-with-Arm-Lift.gif'),
    ('Front Pulldown', 'Back', True, 'Front-Pulldown.gif'),
    ('Front Squat', 'Legs', True, 'front-squat.gif'),
    ('Front to Side Plank', 'Abs', False, 'Front-to-Side-Plank.gif'),
    ('Full Crunch Machine', 'Abs', True, 'Full-Crunch-Machine.gif'),
    ('Full Range Of Motion Lat Pulldown', 'Back', True, 'Full-Range-Of-Motion-Lat-Pulldown.gif'),
    ('Hack Machine One Leg Calves Raise', 'Calves', True, 'Hack-Machine-One-Leg-Calves-Raise.gif'),
    ('Hack Squat Calves Raise', 'Calves', True, 'Hack-Squat-Calves-Raise.gif'),
    ('Half Arnold Press', 'Shoulders', True, 'Half-Arnold-Press.gif'),
    ('Half Kneeling Cable External Rotation', 'Shoulders', True, 'Half-Kneeling-Cable-External-Rotation.gif'),
    ('Half Kneeling High Cable Row Rope', 'Back', True, 'Half-Kneeling-High-Cable-Row-Rope.gif'),
    ('Half Kneeling Lat Pulldown', 'Back', True, 'Half-Kneeling-Lat-Pulldown.gif'),
    ('Hammer Curl', 'Biceps', True, 'Hammer-Curl.gif'),
    ('Hammer Curl with Resistance Band', 'Biceps', False, 'Hammer-Curl-with-Resistance-Band.gif'),
    ('Hamstrings Lying Stretch', 'Legs', False, 'Hamstrings-Lying-Stretch.gif'),
    ('Hand Gripper', 'Forearms', False, 'Hand-Gripper.gif'),
    ('Hands Bike', 'Cardio', False, 'Hands-Bike.gif'),
    ('Handstand Push Up', 'Shoulders', True, 'handstand-push-up.gif'),
    ('Hanging Knee Raises', 'Abs', True, 'Hanging-Knee-Raises.gif'),
    ('Hanging Leg Raises', 'Abs', True, 'Hanging-Leg-Raises.gif'),
    ('Hanging Side Knee Raises', 'Abs', True, 'Hanging-Side-Knee-Raises.gif'),
    ('Hanging Windshield Wiper', 'Abs', True, 'Hanging-Windshield-Wiper.gif'),
    ('Hawaiian Squat', 'Legs', False, 'Hawaiian-Squat-exercise.gif'),
    ('Heel Touch', 'Abs', False, 'Heel-Touch.gif'),
    ('High Cable Crossover', 'Chest', True, 'High-Cable-Crossover.gif'),
    ('High Cable Single Arm Bicep Curl', 'Biceps', True, 'High-Cable-Single-Arm-Bicep-Curl.gif'),
    ('High Knee Run', 'Cardio', False, 'High-Knee-Run.gif'),
    ('High Knees against Wall', 'Cardio', False, 'High-Knees-against-wall.gif'),
    ('High Knee Skips', 'Cardio', False, 'High-Knee-Skips_Cardio.gif'),
    ('High Knee Squat', 'Cardio', False, 'High-Knee-Squat.gif'),
    ('High Pulley Overhead Tricep Extension', 'Triceps', True, 'High-Pulley-Overhead-Tricep-Extension.gif'),
    ('Hook Kick (Kickboxing with Boxing Bag)', 'Legs', True, 'Hook-Kick-Kickboxing-with-boxing-bag.gif'),
    ('Impossible Dips', 'Triceps', True, 'Impossible-Dips.gif'),
    ('Inchworm', 'Cardio', False, 'Inchworm.gif'),
    ('Incline Barbell Bench Press', 'Chest', True, 'Incline-Barbell-Bench-Press.gif'),
    ('Incline Barbell Row', 'Back', True, 'Incline-Barbell-Row.gif'),
    ('Incline Cable Row', 'Back', True, 'Incline-Cable-Row.gif'),
    ('Incline Chest Fly Machine', 'Chest', True, 'Incline-Chest-Fly-Machine.gif'),
    ('Incline Dumbbell Hammer Press', 'Chest', True, 'Incline-Dumbbell-Hammer-Press.gif'),
    ('Incline Dumbbell Fly', 'Chest', True, 'Incline-dumbbell-Fly.gif'),
    ('Incline Dumbbell Press', 'Chest', True, 'Incline-Dumbbell-Press.gif'),
    ('Incline Dumbbell Side Lateral Raise', 'Shoulders', True, 'Incline-Dumbbell-Side-Lateral-Raise.gif'),
    ('Incline Dumbbell Y Raise', 'Shoulders', True, 'Incline-Dumbbell-Y-Raise.gif'),
    ('Incline Leg Hip Raise', 'Abs', True, 'Incline-Leg-Hip-Raise.gif'),
    ('Incline Push-Up', 'Chest', True, 'Incline-Push-Up.gif'),
    ('Incline Reverse Grip Dumbbell Row', 'Back', True, 'Incline-Reverse-Grip-Dumbbell-Row.gif'),
    ('Incline Treadmill', 'Cardio', True, 'Incline-Treadmill.gif'),
    ('Inner Chest Press Machine', 'Chest', True, 'Inner-Chest-Press-Machine.gif'),
    ('Inner Thigh Side Stretch', 'Legs', False, 'INNER-THIGH-SIDE-STRETCH.gif'),
    ('Inverted Row', 'Back', True, 'Inverted-Row.gif'),
    ('Jab Boxing', 'Cardio', False, 'Jab-Boxing.gif'),
    ('Jack Burpees', 'Cardio', False, 'Jack-Burpees.gif'),
    ('Jumping Jack', 'Cardio', False, 'Jumping-jack.gif'),
    ('Jump Rope', 'Cardio', False, 'Jump-Rope.gif'),
    ('Jump Squat', 'Legs', False, 'Jump-Squat.gif'),
    ('Kettlebell Arnold Press', 'Shoulders', True, 'Kettlebell-Arnold-Press.gif'),
    ('Kettlebell Bent-Over Row', 'Back', True, 'Kettlebell-Bent-Over-Row.gif'),
    ('Kettlebell Chest Press on the Floor', 'Chest', True, 'Kettlebell-Chest-Press-on-the-Floor.gif'),
    ('Kettlebell Clean and Jerk', 'Cardio', True, 'Kettlebell-Clean-and-Jerk.gif'),
    ('Kettlebell One-Arm Military Press', 'Shoulders', True, 'Kettlebell-One-Arm-Military-Press.gif'),
    ('Kettlebell Pistol Squats', 'Legs', True, 'Kettlebell-Pistol-Squats.gif'),
    ('Kettlebell Split Snatch', 'Cardio', True, 'Kettlebell-Split-Snatch.gif'),
    ('Kettlebell Swings', 'Cardio', True, 'Kettlebell-Swings.gif'),
    ('Kettlebell Windmill', 'Cardio', True, 'Kettlebell-Windmill.gif'),
    ('Kneeling Cable Crunch', 'Abs', True, 'Kneeling-Cable-Crunch.gif'),
    ('Kneeling Cable Extension', 'Triceps', True, 'Kneeling-Cable-Extension.gif'),
    ('Kneeling High Pulley Row', 'Back', True, 'Kneeling-High-Pulley-Row.gif'),
    ('Kneeling Neck Stretch', 'Neck', False, 'Kneeling-Neck-Stretch.gif'),
    ('Kneeling Push Up', 'Chest', False, 'Kneeling-Push-up.gif'),
    ('Kneeling Quad Stretch', 'Legs', False, 'Kneeling-Quad-Stretch.gif'),
    ('Kneeling Single Arm High Pulley Row', 'Back', True, 'Kneeling-Single-Arm-High-Pulley-Row.gif'),
    ('Knee Push-Up', 'Chest', False, 'Knee-Push-Up.gif'),
    ('Korean Dips', 'Triceps', True, 'Korean-Dips.gif'),
    ('Landmine Lateral Raise', 'Shoulders', True, 'Landmine-Lateral-Raise.gif'),
    ('Landmine Press', 'Shoulders', True, 'Landmine-Press.gif'),
    ('Lateral Raise Machine', 'Shoulders', True, 'Lateral-Raise-Machine.gif'),
    ('Lateral Speed Step', 'Cardio', False, 'Lateral-Speed-Step.gif'),
    ('Lateral Step Up', 'Legs', False, 'Lateral-Step-up.gif'),
    ('Lat Pulldown', 'Back', True, 'Lat-Pulldown.gif'),
    ('Leaning Cable Lateral Raise', 'Shoulders', True, 'Leaning-Cable-Lateral-Raise.gif'),
    ('Leaning Single-Arm Dumbbell Lateral Raise', 'Shoulders', True, 'Leaning-Single-Arm-Dumbbell-Lateral-Raise.gif'),
    ('Leg Curl', 'Legs', True, 'Leg-Curl.gif'),
    ('Leg Extension', 'Legs', True, 'LEG-EXTENSION.gif'),
    ('Leg Press', 'Legs', True, 'Leg-Press.gif'),
    ('Leg Press Calves Raise', 'Legs', True, 'Leg-Press-Calves-Raise.gif'),
    ('Leg Raise Dragon Flag', 'Abs', True, 'Leg-Raise-Dragon-Flag.gif'),
    ('Lever Biceps Curl', 'Biceps', True, 'Lever-Biceps-Curl.gif'),
    ('Lever Cable Rear Pulldown', 'Back', True, 'Lever-Cable-Rear-Pulldown.gif'),
    ('Lever Chest Press', 'Chest', True, 'Lever-Chest-Press.gif'),
    ('Lever Crossovers', 'Chest', True, 'Lever-Crossovers.gif'),
    ('Lever Deadlift', 'Legs', True, 'Lever-Deadlift.gif'),
    ('Lever Donkey Calves Raise', 'Legs', True, 'Lever-Donkey-Calves-Raise.gif'),
    ('Lever Gripless Shrug', 'Shoulders', True, 'Lever-Gripless-Shrug.gif'),
    ('Lever Incline Chest Press', 'Chest', True, 'Lever-Incline-Chest-Press.gif'),
    ('Lever Incline Hammer Chest Press', 'Chest', True, 'Lever-Incline-Hammer-Chest-Press.gif'),
    ('Lever Lateral Raise', 'Shoulders', True, 'Lever-Lateral-Raise.gif'),
    ('Lever Lying Crunch', 'Abs', True, 'Lever-Lying-Crunch.gif'),
    ('Lever Neck Extension (Plate Loaded)', 'Neck', True, 'Lever-Neck-Extension-plate-loaded.gif'),
    ('Lever Neck Right Side Flexion (Plate Loaded)', 'Neck', True, 'Lever-Neck-Right-Side-Flexion-plate-loaded.gif'),
    ('Lever One-Arm Chest Press', 'Chest', True, 'Lever-One-Arm-Chest-Press.gif'),
    ('Lever Overhand Triceps Dip', 'Triceps', True, 'Lever-Overhand-Triceps-Dip.gif'),
    ('Lever Preacher Curl', 'Biceps', True, 'Lever-Preacher-Curl.gif'),
    ('Lever Reverse T-Bar Row', 'Back', True, 'Lever-Reverse-T-Bar-Row.gif'),
    ('Lever Seated Calves Raise', 'Legs', True, 'Lever-Seated-Calves-Raise.gif'),
    ('Lever Seated Twist', 'Abs', True, 'Lever-Seated-Twist.gif'),
    ('Lever Shoulder Press', 'Shoulders', True, 'Lever-Shoulder-Press.gif'),
    ('Lever Shrug', 'Shoulders', True, 'Lever-Shrug.gif'),
    ('Lever Side Hip Abduction', 'Legs', True, 'Lever-Side-Hip-Abduction.gif'),
    ('Lever Side Hip Adduction', 'Legs', True, 'Lever-Side-Hip-Adduction.gif'),
    ('Lever Standing Leg Raise', 'Legs', True, 'Lever-Standing-Leg-Raise.gif'),
    ('Lever T-bar Row', 'Back', True, 'Lever-T-bar-Row.gif'),
    ('Lever Tricep Extension', 'Triceps', True, 'Lever-Tricep-Extension.gif'),
    ('Long Jump Plyometrics', 'Legs', False, 'Long-Jump-Plyometrics.gif'),
    ('Low Cable Crossover', 'Chest', True, 'Low-Cable-Crossover.gif'),
    ('L Sit', 'Abs', False, 'L-Sit.gif'),
    ('Lunging Straight Leg Calves Stretch', 'Legs', False, 'Lunging-Straight-Leg-Calves-Stretch.gif'),
    ('Lying Cable Curl', 'Biceps', True, 'Lying-cable-curl.gif'),
    ('Lying Cable Fly', 'Chest', True, 'Lying-Cable-Fly.gif'),
    ('Lying Cable Reverse Fly', 'Back', True, 'Lying-Cable-Reverse-Fly.gif'),
    ('Lying Chest Press Machine', 'Chest', True, 'Lying-Chest-Press-Machine.gif'),
    ('Lying Dumbbell Leg Curl', 'Legs', True, 'Lying-Dumbbell-Leg-Curl.gif'),
    ('Lying Extension Pullover', 'Back', True, 'Lying-Extension-Pullover.gif'),
    ('Lying Glute Stretch', 'Legs', False, 'Lying-glute-stretch.gif'),
    ('Lying High Bench Barbell Curl', 'Biceps', True, 'Lying-High-Bench-Barbell-Curl.gif'),
    ('Lying Knee Raise', 'Abs', True, 'Lying-Knee-Raise.gif'),
    ('Lying Leg Raise', 'Abs', True, 'Lying-Leg-Raise.gif'),
    ('Lying Scissor Kick', 'Abs', False, 'Lying-Scissor-Kick.gif'),
    ('Lying Shoulder Press', 'Shoulders', True, 'Lying-Shoulder-Press.gif'),
    ('Lying Weighted Lateral Neck Flexion', 'Neck', True, 'Lying-Weighted-Lateral-Neck-Flexion.gif'),
    ('Lying Weighted Neck Extension', 'Neck', True, 'Lying-Weighted-Neck-Extension.gif'),
    ('Lying Weighted Neck Flexion', 'Neck', True, 'Lying-Weighted-Neck-Flexion.gif'),
    ('Mountain Climber', 'Cardio', False, 'Mountain-climber.gif'),
    ('Muscle-Up on Vertical Bar', 'Back', True, 'Muscle-up-vertical-bar.gif'),
    ('Narrow Grip Wall Push-Up', 'Chest', False, 'Narrow-Grip-Wall-Push-Up.gif'),
    ('Navy Seal Burpee', 'Cardio', False, 'Navy-Seal-Burpee.gif'),
    ('Neck Extension Abs', 'Neck', False, 'Neck-Extension-Abs-360x360.png'),
    ('Neck Flexion Abs', 'Neck', False, 'Neck-Flexion-Stretch-360x360.png'),
    ('Oblique Floor Crunches', 'Abs', False, 'Oblique-Floor-Crunches.gif'),
    ('One Arm Decline Cable Fly', 'Chest', True, 'One-Arm-Decline-Cable-Fly.gif'),
    ('One Arm Barbell Row', 'Back', True, 'One-Arm-Barbell-Row-.gif'),
    ('One Arm Bent Over Cable Lateral Raise', 'Shoulders', True, 'One-Arm-Bent-Over-Cable-Lateral-Raise.gif'),
    ('One Arm Biceps Curl', 'Biceps', True, 'One-Arm-Biceps-Curl.gif'),
    ('One Arm Biceps Curl 1', 'Biceps', True, 'One-Arm-Biceps-Curl-1.gif'),
    ('One Arm Cable Bicep Curl', 'Biceps', True, 'One-Arm-Cable-Bicep-Curl.gif'),
    ('One Arm Cable Chest Press', 'Chest', True, 'One-Arm-Cable-Chest-Press.gif'),
    ('One Arm Cable Curl', 'Biceps', True, 'One-Arm-Cable-Curl.gif'),
    ('One Arm Cable Row', 'Back', True, 'One-arm-Cable-Row.gif'),
    ('One Arm Chin-Up', 'Back', True, 'One-Arm-Chin-Up.gif'),
    ('One Arm Dumbbell Upright Row', 'Shoulders', True, 'One-Arm-Dumbbell-Upright-Row.gif'),
    ('One Arm Kettlebell Chest Press on the Bench', 'Chest', True, 'One-Arm-Kettlebell-Chest-Press-on-the-Bench.gif'),
    ('One Arm Kettlebell Snatch', 'Cardio', True, 'One-Arm-Kettlebell-Snatch-exercise.gif'),
    ('One Arm Landmine Row', 'Back', True, 'One-Arm-Landmine-Row.gif'),
    ('One Arm Lying Triceps Extension', 'Triceps', True, 'One-Arm-Lying-Triceps-Extension.gif'),
    ('One Arm Pronated Dumbbell Triceps Extension', 'Triceps', True, 'One-Arm-Pronated-Dumbbell-Triceps-Extension-.gif'),
    ('One Arm Prone Dumbbell Curl', 'Biceps', True, 'One-Arm-Prone-Dumbbell-Curl.gif'),
    ('One Arm Push-Ups With Support', 'Chest', False, 'One-Arm-Push-Ups-With-Support.gif'),
    ('One Arm Reverse Push Down', 'Triceps', True, 'One-Arm-Reverse-Push-Down.gif'),
    ('One Arm Triceps Pushdown', 'Triceps', True, 'One-arm-triceps-pushdown.gif'),
    ('Overhead Cable Curl', 'Biceps', True, 'overhead-cable-curl.gif'),
    ('Overhead Shrug', 'Back', True, 'overhead-shrug.gif'),
    ('Parallel Bar Dip', 'Triceps', True, 'parallel-bar-dip.gif'),
    ('Pec Deck Fly', 'Chest', True, 'Pec-Deck-Fly.gif'),
    ('Pike Push Up', 'Shoulders', False, 'Pike-Push-up.gif'),
    ('Pistol Squat', 'Legs', False, 'Pistol-Squat.gif'),
    ('Plank', 'Abs', False, 'plank.gif'),
    ('Plank with Arm and Leg Lift', 'Abs', False, 'Plank-with-Arm-and-Leg-Lift.gif'),
    ('Plyo Jacks', 'Cardio', False, 'Plyo-Jacks.gif'),
    ('Posterior Tibialis Stretch', 'Legs', False, 'Posterior-Tibialis-Stretch.gif'),
    ('Power Lunge', 'Legs', False, 'Power-Lunge.gif'),
    ('Power Skips', 'Cardio', False, 'Power-Skips.gif'),
    ('Prone Cervical Extension', 'Neck', False, 'Prone-Cervical-Extension.gif'),
    ('Prone Incline Biceps Curl', 'Biceps', True, 'Prone-Incline-Biceps-Curl.gif'),
    ('Pull-up', 'Back', True, 'Pull-up.gif'),
    ('Punches', 'Cardio', False, 'Punches.gif'),
    ('Pushdown', 'Triceps', True, 'Pushdown.gif'),
    ('Push Press 1', 'Shoulders', True, 'push-press-1.gif'),
    ('Push Up with Medicine Ball', 'Chest', True, 'Push-Up-Medicine-Ball.gif'),
    ('Push-Up Plus', 'Chest', False, 'Push-Up-Plus.gif'),
    ('Push-up Toe Touch', 'Chest', False, 'Push-up-Toe-Touch.gif'),
    ('Push Up with Push Up Bars', 'Chest', True, 'Push-up-With-Push-up-Bars.gif'),
    ('Quarter Sit Up', 'Abs', False, 'Quarter-Sit-up.gif'),
    ('Reaction Ball Throw (Agility Ball Drill)', 'Cardio', True, 'Reaction-Ball-Throw-Agility-Ball-Drill-.gif'),
    ('Rear Delt Machine Flys', 'Shoulders', True, 'Rear-Delt-Machine-Flys.gif'),
    ('Recumbent Exercise Bike', 'Cardio', True, 'Recumbent-Exercise-Bike.gif'),
    ('Resistance Band Bent Over Rear Delt Fly', 'Shoulders', True, 'Resistance-Band-Bent-Over-Rear-Delt-Fly.gif'),
    ('Resistance Band Foot External Rotation', 'Calves', True, 'Resistance-Band-Foot-External-Rotation.gif'),
    ('Resistance Band Pull Apart', 'Shoulders', True, 'Resistance-Band-Pull-Apart.gif'),
    ('Reverse Crunch 1', 'Abs', False, 'Reverse-Crunch-1.gif'),
    ('Reverse Grip Barbell Row', 'Back', True, 'Reverse-Grip-Barbell-Row.gif'),
    ('Reverse Grip Dumbbell Bench Press', 'Chest', True, 'Reverse-Grip-Dumbbell-Bench-Press.gif'),
    ('Reverse Grip EZ Bar Curl', 'Biceps', True, 'Reverse-Grip-EZ-Bar-Curl.gif'),
    ('Reverse Grip Incline Dumbbell Press', 'Chest', True, 'Reverse-Grip-Incline-Dumbbell-Press.gif'),
    ('Reverse Grip Machine Row', 'Back', True, 'Reverse-Grip-Machine-Row.gif'),
    ('Reverse Grip Pull-up', 'Back', True, 'Reverse-grip-Pull-up.gif'),
    ('Reverse Grip Pushdown', 'Triceps', True, 'Reverse-Grip-Pushdown.gif'),
    ('Reverse Lat Pulldown', 'Back', True, 'Reverse-Lat-Pulldown.gif'),
    ('Reverse Lunge Knee', 'Legs', True, 'Reverse-Lunge-Knee.gif'),
    ('Reverse Plank', 'Abs', False, 'Reverse-plank.gif'),
    ('Reverse Push-up', 'Chest', True, 'Reverse-Push-up.gif'),
    ('Reverse Wrist Curl', 'Forearms', True, 'Reverse-Wrist-Curl.gif'),
    ('Reverse Wrist Stretch', 'Forearms', False, 'reverse-Wrist-Stretch.gif'),
    ('Riding Outdoor Bicycle', 'Cardio', False, 'Riding-Outdoor-Bicycle.gif'),
    ('Right Cross Boxing', 'Cardio', False, 'Right-Cross-Boxing.gif'),
    ('Right Uppercut Boxing', 'Cardio', False, 'Right-Uppercut-Boxing.gif'),
    ('Ring Inverted Row', 'Back', True, 'Ring-Inverted-Row.gif'),
    ('Roll Rhomboids', 'Back', True, 'Roll-Rhomboids.gif'),
    ('Rope Straight Arm Pulldown', 'Back', True, 'Rope-Straight-Arm-Pulldown.gif'),
    ('Rope Bicep Curls', 'Biceps', True, 'rope-bicep-curls.gif'),
    ('Rope Climb', 'Back', True, 'Rope-Climb.gif'),
    ('Rope Pushdown', 'Triceps', True, 'Rope-Pushdown.gif'),
    ('Rotating Neck Stretch', 'Neck', False, 'Rotating-Neck-Stretch.gif'),
    ('Rowing Machine', 'Cardio', True, 'Rowing-Machine.gif'),
    ('Run', 'Cardio', False, 'Run.gif'),
    ('Run in Place', 'Cardio', False, 'Run-in-Place.gif'),
    ('Run in Place Exercise', 'Cardio', False, 'Run-in-Place-exercise.gif'),
    ('Russian Twist', 'Abs', False, 'Russian-Twist.gif'),
    ('Scapula Dips', 'Shoulders', True, 'Scapula-Dips.gif'),
    ('Scapula Pull Up', 'Back', True, 'Scapula-Pull-up.gif'),
    ('Scapular Protraction and Retraction', 'Back', False, 'Scapular-Protraction-and-Retraction.gif'),
    ('Scott Press', 'Shoulders', True, 'scott-press.gif'),
    ('Seated Adductor Groin Stretch', 'Legs', False, 'Seated-Adductor-Groin-Stretch.gif'),
    ('Seated Ballerina', 'Abs', False, 'Seated-Ballerina.gif'),
    ('Seated Behind The Neck Press', 'Shoulders', True, 'Seated-Behind-the-Neck-Press.gif'),
    ('Seated Bench Leg Pull In', 'Abs', True, 'Seated-Bench-Leg-Pull-in.gif'),
    ('Seated Bicep Curl With Resistance Band', 'Biceps', False, 'Seated-Bicep-Curl-With-Resistance-Band.gif'),
    ('Seated Biceps Curl', 'Biceps', True, 'seated-biceps-curl.gif'),
    ('Seated Cable Rope Row', 'Back', True, 'Seated-Cable-Rope-Row.gif'),
    ('Seated Cable Row', 'Back', True, 'Seated-Cable-Row.gif'),
    ('Seated Calves Press on Leg Press Machine', 'Calves', True, 'Seated-Calves-Press-on-Leg-Press-Machine.gif'),
    ('Seated Close Grip Concentration Curl', 'Biceps', True, 'Seated-close-grip-concentration-curl.gif'),
    ('Seated Dumbbell Alternating Curl', 'Biceps', True, 'seated-dumbbell-alternating-curl.gif'),
    ('Seated Dumbbell Front Raise', 'Shoulders', True, 'seated-dumbbell-front-raise.gif'),
    ('Seated Dumbbell Lateral Raise', 'Shoulders', True, 'Seated-Dumbbell-Lateral-Raise.gif'),
    ('Seated Dumbbell Triceps Extension', 'Triceps', True, 'Seated-Dumbbell-Triceps-Extension.gif'),
    ('Seated EZ Bar Overhead Triceps Extension', 'Triceps', True, 'Seated-EZ-Bar-Overhead-Triceps-Extension.gif'),
    ('Seated Hammer Curl', 'Biceps', True, 'Seated-Hammer-Curl.gif'),
    ('Seated Hamstring Stretch', 'Legs', False, 'Seated-Hamstring-Stretch.gif'),
    ('Seated Incline Dumbbell Curl', 'Biceps', True, 'Seated-Incline-Dumbbell-Curl.gif'),
    ('Seated Leg Curl', 'Legs', True, 'Seated-Leg-Curl.gif'),
    ('Seated Oblique Twist', 'Abs', True, 'Seated-Oblique-Twist.gif'),
    ('Seated One-Arm Dumbbell Triceps Extension', 'Biceps', True, 'Seated-One-Arm-Dumbbell-Triceps-Extension.gif'),
    ('Seated Rear Lateral Dumbbell Raise', 'Shoulders', True, 'Seated-Rear-Lateral-Dumbbell-Raise.gif'),
    ('Seated Row Machine', 'Back', True, 'Seated-Row-Machine.gif'),
    ('Seated Scapular Retraction Exercise', 'Back', True, 'Seated-Scapular-Retraction-Exercise.gif'),
    ('Seated Side Crunches', 'Abs', True, 'Seated-Side-Crunches.gif'),
    ('Seated Straight Leg Calves Stretch', 'Calves', False, 'Seated-Straight-Leg-Calves-Stretch.gif'),
    ('Seated Zottman Curl', 'Biceps', True, 'Seated-Zottman-Curl.gif'),
    ('Serratus Wall Slide With Foam Roller', 'Abs', False, 'Serratus-Wall-Slide-With-Foam-Roller.gif'),
    ('Shadow Boxing Workout', 'Cardio', False, 'shadow-boxing-workout.gif'),
    ('Short Stride Run', 'Cardio', False, 'Short-Stride-Run.gif'),
    ('Shotgun Row', 'Back', True, 'shotgun-row.gif'),
    ('Shoulder Stretch Behind Back', 'Shoulders', False, 'Shoulder-Stretch-Behind-Back.gif'),
    ('Side Bridge', 'Abs', False, 'Side-Bridge.gif'),
    ('Side Lunge Stretch', 'Legs', False, 'Side-Lunge-Stretch.gif'),
    ('Side Neck Stretch', 'Neck', False, 'Side-Neck-Stretch.gif'),
    ('Side Plank', 'Abs', False, 'Side-Plank-1-360x360.png'),
    ('Side Push Neck Stretch', 'Neck', False, 'Side-Push-Neck-Stretch.gif'),
    ('Side Shuttle', 'Cardio', False, 'Side-Shuttle.gif'),
    ('Single Leg Hip Thrust Jump', 'Legs', True, 'Single-Leg-Hip-Thrust-Jump.gif'),
    ('Single Arm Cable Crossover', 'Chest', True, 'Single-Arm-Cable-Crossover.gif'),
    ('Single Arm Circles', 'Biceps', True, 'Single-Arm-Circles.gif'),
    ('Single Arm Push Up', 'Chest', False, 'Single-Arm-Push-up.gif'),
    ('Single-Arm Reverse-Grip Cable Bicep Curl', 'Biceps', True, 'Single-Arm-Reverse-Grip-Cable-Bicep-Curl.gif'),
    ('Single Calves Raise on Leg Press Machine', 'Calves', True, 'Single-Calves-Raise-on-Leg-Press-Machine.gif'),
    ('Single Dumbbell Close Grip Press', 'Chest', True, 'Single-Dumbbell-Close-grip-Press.gif'),
    ('Single Dumbbell Spider Hammer Curl', 'Biceps', True, 'Single-Dumbbell-Spider-Hammer-Curl.gif'),
    ('Single Heel Drop Calves Stretch', 'Calves', False, 'Single-Heel-Drop-Calves-Stretch.gif'),
    ('Single Leg Box Jump', 'Legs', True, 'Single-Leg-Box-Jump.gif'),
    ('Single Leg Broad Jump', 'Legs', True, 'Single-Leg-Broad-Jump.gif'),
    ('Single Leg Calves Raises', 'Calves', True, 'Single-Leg-Calves-Raises.gif'),
    ('Single Leg Calves Stretch', 'Calves', False, 'Single-Leg-Calves-Stretch.gif'),
    ('Single Leg Donkey Calves Raise', 'Calves', True, 'Single-Leg-Donkey-Calves-Raise.gif'),
    ('Sit Ups', 'Abs', False, 'Sit-ups.gif'),
    ('Skater', 'Cardio', False, 'Skater.gif'),
    ('Ski Step', 'Cardio', False, 'Ski-Step.gif'),
    ('Sled Hack Squat', 'Legs', True, 'Sled-Hack-Squat.gif'),
    ('Smith Machine Behind Neck Press', 'Shoulders', True, 'Smith-Machine-Behind-Neck-Press.gif'),
    ('Smith Machine Bench Press', 'Chest', True, 'Smith-Machine-Bench-Press.gif'),
    ('Smith Machine Bent Over Row', 'Back', True, 'Smith-Machine-Bent-Over-Row.gif'),
    ('Smith Machine Decline Bench Press', 'Chest', True, 'Smith-Machine-Decline-Bench-Press.gif'),
    ('Smith Machine Good Morning', 'Legs', True, 'Smith-Machine-Good-Morning.gif'),
    ('Smith Machine Hex Press', 'Chest', True, 'Smith-Machine-Hex-Press.gif'),
    ('Smith Machine Incline Bench Press', 'Chest', True, 'Smith-Machine-Incline-Bench-Press.gif'),
    ('Smith Machine Shoulder Press', 'Shoulders', True, 'Smith-Machine-Shoulder-Press.gif'),
    ('Smith Machine Shrug', 'Back', True, 'smith-machine-shrug.gif'),
    ('Snap Jumps', 'Cardio', False, 'SNAP-JUMPS.gif'),
    ('Sphinx Stretch', 'Abs', False, 'Sphinx-Stretch.gif'),
    ('Spider Plank', 'Abs', False, 'Spider-Plank.gif'),
    ('Split Jacks', 'Cardio', False, 'Split-Jacks.gif'),
    ('Split Squat', 'Legs', False, 'Split-Squat.gif'),
    ('Sprint', 'Cardio', False, 'sprint.gif'),
    ('Squat Hold Calves Raise', 'Calves', False, 'Squat-Hold-Calves-Raise.gif'),
    ('Squat Tuck Jump', 'Legs', False, 'Squat-Tuck-Jump.gif'),
    ('Stability Ball Decline Push-Ups', 'Chest', False, 'stability-ball-decline-push-ups.gif'),
    ('Stability Ball Knee Tuck', 'Abs', False, 'Stability-Ball-Knee-Tuck.gif'),
    ('Stability Ball Push Up', 'Chest', False, 'stability-ball-push-up.gif'),
    ('Standing Alternating Dumbbell Shoulder Press', 'Shoulders', True, 'Standing-Alternating-Dumbbell-Shoulder-Press.gif'),
    ('Standing Barbell Calves Raise', 'Legs', True, 'Standing-Barbell-Calves-Raise.gif'),
    ('Standing Barbell Close Grip Military Press', 'Shoulders', True, 'Standing-Barbell-Close-Grip-Military-Press.gif'),
    ('Standing Barbell Concentration Curl', 'Biceps', True, 'Standing-Barbell-Concentration-Curl.gif'),
    ('Standing Barbell Triceps Extension', 'Triceps', True, 'Standing-Barbell-Triceps-Extension.gif'),
    ('Standing Cable Crunch', 'Abs', True, 'Standing-Cable-Crunch.gif'),
    ('Standing Cable High-To-Low Twist', 'Abs', True, 'Standing-Cable-High-To-Low-Twist.gif'),
    ('Standing Cable Low-to-High Twist', 'Abs', True, 'Standing-Cable-low-to-high-Twist.gif'),
    ('Standing Cable Twist', 'Abs', True, 'standing-cable-twist.gif'),
    ('Standing Calves Raise', 'Calves', True, 'Standing-Calves-Raise.gif'),
    ('Standing Cross Leg Hamstring Stretch', 'Legs', False, 'Standing-Cross-Leg-Hamstring-Stretch.gif'),
    ('Standing Dorsiflexion', 'Calves', False, 'Standing-Dorsiflexion.gif'),
    ('Standing Dumbbell Overhead Press', 'Shoulders', True, 'Standing-Dumbbell-Overhead-Press.gif'),
    ('Standing Gastrocnemius Calves Stretch', 'Calves', False, 'Standing-Gastrocnemius-Calves-Stretch.gif'),
    ('Standing Hamstring Stretch', 'Legs', False, 'Standing-Hamstring-Stretch.gif'),
    ('Standing Leg Circles', 'Legs', False, 'Standing-Leg-Circles.gif'),
    ('Standing Medicine Ball Chest Pass', 'Chest', True, 'Standing-Medicine-Ball-Chest-Pass.gif'),
    ('Standing One-Arm Chest Stretch', 'Chest', False, 'Standing-one-arm-chest-stretch.gif'),
    ('Standing Reach-Up Back Rotation Stretch', 'Abs', False, 'Standing-Reach-Up-Back-rotation-Stretch.gif'),
    ('Standing Reverse Shoulder Stretch', 'Shoulders', False, 'Standing-Reverse-Shoulder-Stretch.gif'),
    ('Standing Rotation', 'Abs', False, 'Standing-Rotation.gif'),
    ('Standing Side Bend Stretch', 'Abs', False, 'Standing-Side-Bend-Stretch.gif'),
    ('Standing Single-Arm Upright Row', 'Shoulders', True, 'Standing-Single-Arm-Upright-Row.gif'),
    ('Standing Smith Machine Shoulder Press', 'Shoulders', True, 'Standing-Smith-Machine-Shoulder-Press.gif'),
    ('Standing Toe Flexor Stretch', 'Calves', False, 'Standing-Toe-Flexor-Stretch.gif'),
    ('Standing Toe Touch', 'Calves', False, 'Standing-Toe-Touch.gif'),
    ('Standing Toe Up Achilles Stretch', 'Calves', False, 'Standing-Toe-Up-Achilles-Stretch.gif'),
    ('Standing Wall Calves Stretch', 'Calves', False, 'Standing-Wall-Calves-Stretch.gif'),
    ('Static Lunge', 'Legs', False, 'Static-Lunge.gif'),
    ('Stationary Bike Run', 'Cardio', False, 'Stationary-Bike-Run.gif'),
    ('Step Up', 'Legs', False, 'Step-up.gif'),
    ('Step Up Opposite Elbow to Knee Twist', 'Abs', False, 'Step-Up-Opposite-Elbow-to-Knee-Twist.gif'),
    ('Straight Bar Dip', 'Triceps', True, 'Straight-Bar-Dip.gif'),
    ('Sumo Plie Dumbbell Squat', 'Legs', True, 'Sumo-Plie-Dumbbell-Squat.gif'),
    ('Superman Exercise', 'Back', False, 'Superman-exercise.gif'),
    ('Svend Press', 'Chest', True, 'Svend-Press.gif'),
    ('Swimming', 'Cardio', False, 'Swimming.gif'),
    ('Swiss Ball Rollout', 'Abs', True, 'swiss-ball-rollout.gif'),
    ('Table Inverted Row', 'Back', True, 'Table-Inverted-Row.gif'),
    ('T Bar Row', 'Back', True, 'T-Bar-Row.gif'),
    ('T Cross Sit Up', 'Abs', False, 'T-Cross-Sit-up.gif'),
    ('Teaser Pilates', 'Abs', False, 'Teaser-Pilates.gif'),
    ('The Box Jump', 'Legs', False, 'The-Box-Jump.gif'),
    ('Toe Extensor Stretch', 'Calves', False, 'Toe-Extensor-Stretch.gif'),
    ('Toes to Bar', 'Abs', True, 'Toes-to-Bar.gif'),
    ('Treadmill', 'Cardio', False, 'Treadmill-.gif'),
    ('Triceps Extension Machine', 'Triceps', True, 'Triceps-Extension-Machine.gif'),
    ('Triceps Dips', 'Triceps', False, 'Triceps-Dips.gif'),
    ('Triceps Dips on Floor', 'Triceps', False, 'Triceps-Dips-on-Floor.gif'),
    ('Triceps Stretch', 'Triceps', False, 'Triceps-Stretch.gif'),
    ('Tuck Crunch', 'Abs', False, 'Tuck-Crunch.gif'),
    ('Tuck Jump', 'Legs', False, 'Tuck-Jump.gif'),
    ('Twisting Hyperextension', 'Back', False, 'Twisting-Hyperextension.gif'),
    ('Two Arm Cable Front Raise', 'Shoulders', True, 'Two-Arm-Cable-Front-Raise.gif'),
    ('Two Arm Cable Lateral Raise', 'Shoulders', True, 'Two-Arm-Cable-Lateral-Raise.gif'),
    ('Two-Arm Dumbbell Front Raise', 'Shoulders', True, 'Two-Arm-Dumbbell-Front-Raise.gif'),
    ('Two Dumbbell Preacher Curl', 'Biceps', True, 'Two-dumbbell-preacher-curl.gif'),
    ('Upavistha Konasana', 'Abs', False, 'Upavistha-Konasana.gif'),
    ('Upper Back Stretch', 'Back', False, 'Upper-Back-Stretch.gif'),
    ('Upside Down Pull Up', 'Back', True, 'Upside-Down-Pull-up.gif'),
    ('V Bar Lat Pulldown', 'Back', True, 'V-bar-Lat-Pulldown.gif'),
    ('Vertical Mountain Climber', 'Cardio', False, 'Vertical-Mountain-Climber.gif'),
    ('Vibrate Plate Standing', 'Legs', True, 'Vibrate-Plate-Standing.gif'),
    ('V Up Down with Stability Ball', 'Abs', False, 'V-Up-Down-with-Stability-ball.gif'),
    ('Waiter Curl', 'Biceps', True, 'waiter-curl.gif'),
    ('Walking', 'Cardio', False, 'Walking.gif'),
    ('Walking High Knee Lunges', 'Legs', False, 'Walking-High-Knee-Lunges.gif'),
    ('Walking on Stepmill', 'Cardio', True, 'Walking-on-Stepmill.gif'),
    ('Walk Wave Machine', 'Cardio', True, 'Walk-Wave-Machine.gif'),
    ('Wall Push Ups', 'Chest', False, 'Wall-Push-ups.gif'),
    ('Wall Sit', 'Legs', False, 'Wall-Sit-238x360.png'),
    ('Wall Supported Handstand Push-up', 'Shoulders', True, 'wall-supported-handstand-push-up.gif'),
    ('Water Bottle Hammer Curl', 'Biceps', False, 'Water-Bottle-Hammer-Curl.gif'),
    ('Weighted Crunch', 'Abs', True, 'Weighted-Crunch.gif'),
    ('Weighted Donkey Calves Raise', 'Legs', True, 'Weighted-Donkey-Calves-Raise.gif'),
    ('Weighted Front Plank', 'Abs', True, 'Weighted-Front-Plank.gif'),
    ('Weighted Hanging Knee Raises', 'Abs', True, 'weighted-hanging-knee-raises.gif'),
    ('Weighted Lying Neck Extension', 'Neck', True, 'Weighted-Lying-Neck-Extension.gif'),
    ('Weighted Lying Neck Flexion', 'Neck', True, 'Weighted-Lying-Neck-Flexion.gif'),
    ('Weighted Lying Twist', 'Abs', True, 'weighted-lying-twist.gif'),
    ('Weighted Neck Harness Extension', 'Neck', True, 'Weighted-Neck-Harness-Extension.gif'),
    ('Weighted One Arm Pull Up', 'Back', True, 'Weighted-One-Arm-Pull-up.gif'),
    ('Weighted Pull Up', 'Back', True, 'Weighted-Pull-up.gif'),
    ('Weighted Push Up', 'Chest', True, 'Weighted-Push-up.gif'),
    ('Weighted Round Arm', 'Shoulders', True, 'weighted-round-arm.gif'),
    ('Weighted Seated Calves Raise', 'Legs', True, 'Weighted-Seated-Calves-Raise.gif'),
    ('Weighted Side Bend on Stability Ball', 'Abs', True, 'Weighted-Side-Bend-on-stability-ball.gif'),
    ('Weighted Sit Ups', 'Abs', True, 'weightedsitups.gif'),
    ('Weighted Wrist Curl', 'Forearms', True, 'Weighted-Wrist-Curl.gif'),
    ('Weight Plate Front Raise', 'Shoulders', True, 'Weight-Plate-Front-Raise-1.gif'),
    ('Wheel Run', 'Cardio', False, 'Wheel-Run.gif'),
    ('Wide Grip Alternate Barbell Bent Over Row Plus', 'Back', True, 'Wide-Grip-Alternate-Barbell-Bent-Over-Row-Plus.gif'),
    ('Wide Grip Barbell Bench Press', 'Chest', True, 'Wide-Grip-Barbell-Bench-Press.gif'),
    ('Wide Grip Barbell Bent Over Row Plus', 'Back', True, 'Wide-Grip-Barbell-Bent-Over-Row-Plus.gif'),
    ('Wrist Circles Stretch', 'Forearms', False, 'Wrist-Circles-Stretch.gif'),
    ('Wrist Roller', 'Forearms', True, 'wrist-roller.gif'),
    ('Wrist Stretch', 'Forearms', False, 'Wrist-Stretch.gif'),
    ('Wrist Ulnar Deviator And Extensor Stretch', 'Forearms', False, 'Wrist-Ulnar-Deviator-And-Extensor-Stretch.gif'),
    ('Z Bar Curl', 'Biceps', True, 'Z-Bar-Curl.gif'),
    ('Z Bar Preacher Curl', 'Biceps', True, 'Z-Bar-Preacher-Curl.gif'),
    ('Zig Zag Hops Plyometric', 'Legs', False, 'Zig-Zag-Hops-Plyometric.gif'),
    ('Zottman Curl', 'Biceps', True, 'zottman-curl.gif');


